@TestOn('vm')
library;

import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:lang_id/lang_id_io.dart';
import 'package:test/test.dart';

/// Cross-check against the original fastText: the reference answers live in
/// test/golden and are regenerated by tool/generate_golden.py.
///
/// This is the package's main test. The implementation is a line-by-line port
/// of C++, and the only way to know the port is right is to compare the
/// numbers against the source of truth.
void main() {
  for (final model in ['lid.176.ftz', 'lid.176.bin']) {
    group(model, () {
      final modelFile = File('models/$model');
      final goldenFile = File('test/golden/${model.replaceAll('.', '_')}.json');

      if (!modelFile.existsSync()) {
        test(
          'skipped: no ${modelFile.path}',
          () {},
          skip:
              'run '
              'dart run tool/download_model.dart'
              '${model.endsWith('.bin') ? ' --full' : ''}',
        );
        return;
      }

      late LanguageIdentifier identifier;
      late Map<String, dynamic> golden;

      setUpAll(() {
        identifier = loadModelSync(modelFile.path);
        golden =
            jsonDecode(goldenFile.readAsStringSync()) as Map<String, dynamic>;
      });

      test('predictions match the reference', () {
        final k = golden['k'] as int;
        final cases = golden['cases'] as List<dynamic>;
        expect(cases, isNotEmpty);

        for (final entry in cases) {
          final testCase = entry as Map<String, dynamic>;
          final text = testCase['text'] as String;
          final expected = (testCase['predictions'] as List<dynamic>)
              .cast<Map<String, dynamic>>();

          final actual = identifier.predict(text, k: k);
          final reason = 'text: ${jsonEncode(text)}';

          expect(actual, hasLength(expected.length), reason: reason);
          for (var i = 0; i < expected.length; i++) {
            expect(actual[i].label, expected[i]['label'], reason: reason);
            expect(
              actual[i].probability,
              closeTo(expected[i]['probability'] as double, 1e-6),
              reason: '$reason, label ${actual[i].label}',
            );
          }
        }
      });

      test('sentence vectors match the reference bit for bit', () {
        for (final entry in golden['cases'] as List<dynamic>) {
          final testCase = entry as Map<String, dynamic>;
          final text = testCase['text'] as String;
          final expected = testCase['sentenceVector'] as String;

          expect(
            _hex(identifier.sentenceVector(text)),
            expected,
            reason: 'text: ${jsonEncode(text)}',
          );
        }
      });
    });
  }
}

/// The raw little-endian bytes of a float32 list, so the comparison is exact
/// rather than rounded through decimal.
String _hex(Float32List values) {
  final bytes = Uint8List.view(
    values.buffer,
    values.offsetInBytes,
    values.lengthInBytes,
  );
  return [
    for (final byte in bytes) byte.toRadixString(16).padLeft(2, '0'),
  ].join();
}
