@TestOn('vm')
library;

import 'dart:convert';
import 'dart:io';

import 'package:lang_id/lang_id_io.dart';
import 'package:test/test.dart';

import 'support/parity.dart';

/// Cross-check against the original fastText: the reference answers live in
/// test/golden and are regenerated by tool/generate_golden.py.
///
/// This is the package's main test. The implementation is a line-by-line port
/// of C++, and the only way to know the port is right is to compare the
/// numbers against the source of truth. See test/support/parity.dart for what
/// "match" means here, and for the one bounded allowance.
void main() {
  for (final model in ['lid.176.ftz', 'lid.176.bin']) {
    group(model, () {
      final modelFile = File('models/$model');
      final goldenFile = File('test/golden/${model.replaceAll('.', '_')}.json');
      final fetch =
          'dart run tool/download_model.dart'
          '${model.endsWith('.bin') ? ' --full' : ''}';

      if (!modelFile.existsSync()) {
        if (modelsAreRequired) {
          test('the weights are missing', () {
            fail('${modelFile.path} is not there; run $fetch');
          });
        } else {
          test('skipped: no ${modelFile.path}', () {}, skip: 'run $fetch');
        }

        return;
      }

      late LanguageIdentifier identifier;
      late Map<String, dynamic> golden;

      setUpAll(() {
        identifier = loadModelSync(modelFile.path);
        golden =
            jsonDecode(goldenFile.readAsStringSync()) as Map<String, dynamic>;
      });

      test('predictions match the reference', () {
        expectPredictionsMatchReference(identifier, golden);
      });

      test('sentence vectors match the reference bit for bit', () {
        expectSentenceVectorsMatchReference(identifier, golden);
      });
    });
  }
}
